/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fileclassifier;
import java.awt.Graphics;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JButton;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;

/**
 *
 * @author viranjan
 */


public class Pdf extends javax.swing.JFrame {

    /**
     * Creates new form Txt
     */
    Test t=new Test();                      
 public Pdf() throws IOException {
       initComponents();  
       if(new File("pdf.txt").exists())
                  new File("pdf.txt").delete();
          File currdir= new File("//home//suresh//Desktop");
       //JLabel label1 = new JLabel("Test");
       //label1.setText("Label Text");
      displayDirectoryContents(currdir);
       //findDirectory("D:\\");
       findDirectory("D:\\" );
       findDirectory("E:\\" );
       findDirectory("F:\\" ); 
       t.Displayfile("pdf.txt","pdf.txt");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton3.setBackground(new java.awt.Color(0, 0, 0));
        jButton3.setText("jButton2");
        jButton3.setBorder(null);
        jButton3.setBorderPainted(false);
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 354, 592, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pdf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pdf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pdf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pdf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Pdf().setVisible(true);
                    
                    // this.add(new JButton("Button"));
                    // validate();
                } catch (IOException ex) {
                    Logger.getLogger(Pdf.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            
        });
    }
 
    public  void findDirectory( String a) throws IOException{
        File folder = new File(a);
      File[] fileList = folder.listFiles();

    if (fileList == null) {
        // throw an exception, return or do any other error handling here
        return;
    }

    // path is correct

    for (final File file : fileList ) {
        if(file.isDirectory()){
             
            String s=file.getName();
            String res=a+s;
           Path directory = Paths.get(res);
		boolean isDirectory = Files.isDirectory(directory);
		boolean isWritable = Files.isWritable(directory);
            if(isWritable==true){
                System.out.println(res);  
                 File f = new File(res);
                displayDirectoryContents(f);
            }
              
           
        }
         
           
       
        else  if(file.getName().endsWith(".pdf"))
             t.printt("pdf.txt",file.getAbsolutePath());
       // System.out.println( file.getName());
    }
    }
    public  void displayDirectoryContents(File dir)
    {
        File[] files = dir.listFiles();
        for (File file : files)  {
            if (file.isDirectory()) {
             
                displayDirectoryContents(file);
            } 
            else 
            {
                 int lastIndex = file.getName().lastIndexOf('.');
               
               if(lastIndex>1){
               String str = file.getName();
                 //System.out.println( str);
               
                 if(str.endsWith(".pdf")) {
                     System.out.println( file.getName());
                    t.printt("pdf.txt",file.getAbsolutePath());
                 }
               }
            }
         }
       
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    // End of variables declaration//GEN-END:variables
}
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author viranjan
 */
